// RootLayoutはNavbarとFooterを含む共通のレイアウトを提供し、
// childrenとして受け取ったページコンポーネント（この場合はHome）を表示します。
// Homeが現在、アクティブなページ：page.tsxになっている。

import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar';
import Footer from '../components/Footer'; // Footerコンポーネントをインポート
import './globals.css'


const inter = Inter({ subsets: ['latin'] })

const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <header>
                <Navbar /> {/* ここでNavbarコンポーネントを使用 */}
      </header>
      {children} {/* 各ページのコンテンツをここに追加、今は index.tsx 読み込み*/}
      <Footer /> {/* Footerコンポーネントを追加 */}
    </>
  )
}
